categories:
  股友说:
    - 股友说
    - 股民
    - 交易高手
    - 短线交易
    - 交易者
    - 炒股的人
  资讯:
    - 板块
    - 涨停
    - 大涨
    - 官宣
    - A股
    - 芯片
    - 指数
    - 主力
  同花顺进行曲:
    - 同花顺进行曲
    - 真英雄
    - 伴奏
    - 合唱
  大佬采访:
    - 采访
    - 冠军
    - 大佬
    - 孙辉
    - 陈小群
    - 鑫多多
  盘点:
    - 盘点
    - 前十
    - 排行
    - VS
  财商动画:
    - 动画
    - 财商
    - 贫穷的人
    - 富有的人
  问财问句:
    - 问财
    - 问句
    - 选股模型
  社区话题:
    - 社区
    - 股民交流
    - 同花顺社区
  励志语录:
    - 阶层跃迁
    - 纪律
    - 一事无成
    - 翻身
    - 先苦后甜
